name: Package Inkscape Extension

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Extension Code
        uses: actions/checkout@v4

      - name: Checkout Library Code
        uses: actions/checkout@v4
        with:
          repository: paulhenry46/pyfeyngen # Remplace par ton vrai pseudo/nom de dépôt
          path: temp_lib

      - name: Prepare Extension Folder
        run: |
          # Créer le dossier de destination dans l'extension
          # Copier uniquement le contenu du dossier src/pyfeyngen
          cp -r temp_lib/src/pyfeyngen/* ./pyfeyngen/
          # Nettoyer le dossier temporaire et les fichiers inutiles (.git, etc.)
          rm -rf temp_lib
          rm -rf .git
          rm -rf .github

      - name: Create Zip Archive
        run: zip -r pyinkfeyn_extension.zip .

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./pyinkfeyn_extension.zip
          asset_name: pyinkfeyn_v${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip