name: Package Inkscape Extension

on:
  release:
    types: [published]

# Ajout des permissions nécessaires pour modifier la release
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Extension Code
        uses: actions/checkout@v4

      - name: Checkout Library Code
        uses: actions/checkout@v4
        with:
          repository: paulhenry46/pyfeyngen
          path: temp_lib

      - name: Prepare Extension Folder
        run: |
          # Créer le dossier de destination si nécessaire et copier la lib
          mkdir -p ./pyfeyngen/
          cp -r temp_lib/src/pyfeyngen/* ./pyfeyngen/
          
          # Nettoyage
          rm -rf temp_lib
          rm -rf .git
          rm -rf .github

      - name: Create Zip Archive
        run: zip -r pyinkfeyn_extension.zip .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          # Spécifie le fichier à uploader
          files: pyinkfeyn_extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}